import React from "react";
import Image from "next/image";
import StatsSidebar from "@/app/stats/sidebar";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return (
        <main className="grid grid-cols-[16rem_1fr] gap-4">
            <StatsSidebar />
            {children}
        </main>
    )
}