import React from "react";
import Image from "next/image";
import StatsSidebar from "@/app/stats/sidebar";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="flex items-center justify-center">
            <main className="w-full grid grid-cols-[16rem_1fr] gap-4 max-w-(--breakpoint-2xl)">
                <StatsSidebar />
                {children}
            </main>
        </div>
    )
}