import './globals.css'
import React from "react";
import NavBar from "@/components/NavBar";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className='bg-linear-to-br from-gray-200 to-gray-100 h-screen'>
        <NavBar />
        <div className="max-w-(--breakpoint-2xl) mx-auto px-4 pt-2 z-10">
            {children}
        </div>
        </body>
        </html>
    )
}