import './globals.css'
import React from "react";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="max-w-screen-2xl mx-auto px-4 pt-2 z-10">
          {children}
        </div>
      </body>
    </html>
  )
}